import mutations from './mutations.js';
import actions from './actions.js';
import getters from './getters.js';

export default {
	namespaced: true,
	state() {
		return {
			exhibitors: [
				{
					id: 'e1',
					boothNumber: 101,
					media: ['natural/organic'],
					businessName: 'Making Good Scentz',
					firstName: 'Steven',
					lastName: 'Stivers',
					city: 'Bardstown',
					state: 'KY',
					phone: '5023648126',
					email: 'orders@makinggoodscentz.com',
					businessUrl: 'www.makinggoodscentz.com',
				},
				{
					id: 'e2',
					boothNumber: 107,
					media: ['wood', 'furniture'],
					businessName: 'Cole & Sons Inc, LLC',
					firstName: 'Andrew',
					lastName: 'Cole',
					city: 'Bowling Green',
					state: 'KY',
					phone: '7658609493',
					email: 'coleandsonsinc@gmail.com',
					businessUrl: 'www.coleandsonsinc.com',
				},
				{
					id: 'e3',
					boothNumber: 111,
					media: ['graphics'],
					businessName: 'Wiggins Artwork',
					firstName: 'Stephen',
					lastName: 'Wiggins',
					city: 'Lexington',
					state: 'KY',
					phone: '8596938172',
					email: 'coleandsonsinc@gmail.com',
					businessUrl: 'www.wigginsartwork.com',
				},
				{
					id: 'e4',
					boothNumber: 113,
					media: ['jewelry'],
					businessName: 'Mark Needham Jewelry',
					firstName: 'Mark',
					lastName: 'Needham',
					city: 'Louisville',
					state: 'KY',
					phone: '5028932851',
					email: 'mark@markneedhamjewelry.com',
					businessUrl: 'www.markneedhamjewelry.com',
				},
				{
					id: 'e5',
					boothNumber: 120,
					media: ['natural/organic'],
					businessName: 'Peace of the Earth, LLC',
					firstName: 'Leslie',
					lastName: 'Delgado',
					city: 'Louisville',
					state: 'KY',
					phone: '5026905707',
					email: 'leslie@peaceoftheearth.com',
					businessUrl: 'www.peaceoftheearth.com',
				},
				{
					id: 'e6',
					boothNumber: 122,
					media: ['ceramics'],
					businessName: 'Star Bird Pottery',
					firstName: 'Caroline',
					lastName: 'Zama',
					city: 'Louisville',
					state: 'KY',
					phone: '5024726533',
					email: 'caroline_zama@yahoo.com',
					businessUrl: 'www.starbirdpottery.com',
				},
				{
					id: 'e7',
					boothNumber: 126,
					media: ['stone'],
					businessName: 'Stone Table Studio',
					firstName: 'Gary',
					lastName: 'DuBois',
					city: 'Berea',
					state: 'KY',
					phone: '8593148407',
					email: 'stonetablestudio@gmail.com',
					businessUrl: 'stonetablestudio.com',
				},
				{
					id: 'e8',
					boothNumber: 128,
					media: ['sculpture', 'wood'],
					businessName: 'Jamie Green Sculpture',
					firstName: 'Jamie',
					lastName: 'Green',
					city: 'Lexington',
					state: 'KY',
					phone: '8594335426',
					email: 'jamiegreensculpture@gmail.com',
					businessUrl: 'www.jamiegreensculpture.com',
				},
				{
					id: 'e9',
					boothNumber: 132,
					media: ['mixed media'],
					businessName: 'Ab Ova Art',
					firstName: 'Barbara',
					lastName: 'Stallard',
					city: 'Louisville',
					state: 'KY',
					phone: '5024349242',
					email: 'bcstallard@hotmail.com',
					businessUrl: 'abovaart.com',
				},
				{
					id: 'e10',
					boothNumber: 134,
					media: ['fiber'],
					businessName: 'Blue Lick Hollow',
					firstName: 'Mary Ann',
					lastName: 'Woolery-Bussey',
					city: 'Berea',
					state: 'KY',
					phone: '8597563003',
					email: 'info@bluelickhollow.com',
					businessUrl: 'www.bluelickhollow.com',
				},
				{
					id: 'e11',
					boothNumber: 140,
					media: ['fiber'],
					businessName: 'Anam Cara Art',
					firstName: 'Peggy',
					lastName: 'Modjeski',
					city: 'Louisville',
					state: 'KY',
					phone: '5027243333',
					email: 'woofsong@gmail.com',
					businessUrl: 'Anamcaraart.com',
				},
				{
					id: 'e12',
					boothNumber: 142,
					media: ['ceramics'],
					businessName: 'Martin Studio',
					firstName: 'John',
					lastName: 'Martin',
					city: 'Beattyville',
					state: 'KY',
					phone: '8596619037',
					email: 'mrtnstudio@gmail.com',
					businessUrl: 'https://www.facebook.com/Martin-Studio-288004391392576/',
				},
				{
					id: 'e13',
					boothNumber: 146,
					media: ['baskets', 'fiber', 'natural/organic'],
					businessName: 'Designer Baskets by Derek',
					firstName: 'Derek',
					lastName: 'Downing',
					city: 'Lexington',
					state: 'KY',
					phone: '8594893400',
					email: 'derek@designerbasketsbyderek.com',
					businessUrl: 'www.designerbasketsbyderek.com',
				},
				{
					id: 'e14',
					boothNumber: 148,
					media: ['fiber', 'natural/organic'],
					businessName: 'Cynthia Houston',
					firstName: 'Cynthia',
					lastName: 'Houston',
					city: 'Bowling Green',
					state: 'KY',
					phone: '2709017315',
					email: 'media3693@aol.com',
					businessUrl: 'cindyhouston.com',
				},
				{
					id: 'e15',
					boothNumber: 150,
					media: ['glass'],
					businessName: 'Chad Balster Glass',
					firstName: 'Chad',
					lastName: 'Balster',
					city: 'Louisville',
					state: 'KY',
					phone: '5023866319',
					email: 'chadbalsterglass@gmail.com',
					businessUrl: 'www.chadbalsterglass.com',
				},
				{
					id: 'e16',
					boothNumber: 152,
					media: ['drawing', 'painting'],
					businessName: 'Art by Kathy Conroy',
					firstName: 'Kathleen',
					lastName: 'Conroy',
					city: 'Pleasureville',
					state: 'KY',
					phone: '5025427208',
					email: 'kathleensr@bellsouth.net',
					businessUrl: 'www.artbykathyconroy.com',
				},
				{
					id: 'e17',
					boothNumber: 158,
					media: ['painting'],
					businessName: 'Mels Art Works',
					firstName: 'Melanie',
					lastName: 'Wisdom',
					city: 'Lexington',
					state: 'KY',
					phone: '6066150022',
					email: 'melsartworks1@gmail.com',
					businessUrl: 'melsartworks.com',
				},
				{
					id: 'e18',
					boothNumber: 160,
					media: ['painting'],
					businessName: 'Ken Burney Art, LLC',
					firstName: 'Kenneth',
					lastName: 'Burney',
					city: 'Lexington',
					state: 'KY',
					phone: '3134097736',
					email: 'kenburneyart@gmail.com',
					businessUrl: 'www.kenburneyart.com',
				},
				{
					id: 'e19',
					boothNumber: 161,
					media: ['ceramics'],
					businessName: 'Egenolf Ceramics',
					firstName: 'Adam',
					lastName: 'Egenolf',
					city: 'Nineveh',
					state: 'IN',
					phone: '8126068775',
					email: 'egenolfceramics@gmail.com',
					businessUrl: 'www.egenolfceramics.com',
				},
				{
					id: 'e20',
					boothNumber: 165,
					media: ['publisher'],
					businessName: 'University Press of Kentucky',
					firstName: '',
					lastName: '',
					city: 'Lexington',
					state: 'KY',
					phone: '8592574249',
					email: 'brooke.raby@uky.edu',
					businessUrl: 'www.kentuckypress.com',
				},
				{
					id: 'e21',
					boothNumber: 169,
					media: ['publisher'],
					businessName: 'Acclaim Press',
					firstName: 'Doug',
					lastName: 'Sikes',
					city: 'Morley',
					state: 'MO',
					phone: '5734729800',
					email: 'dwsikes@acclaimpress.com',
					businessUrl: 'acclaimpress.com',
				},
				{
					id: 'e22',
					boothNumber: 171,
					media: ['publisher'],
					businessName: 'Kentucky Monthly Magazine',
					firstName: 'Stephen',
					lastName: 'Vest',
					city: 'Frankfort',
					state: 'KY',
					phone: '5022270053',
					email: 'kentuckymonthly@kentuckymonthly.com',
					businessUrl: 'kentuckymonthly.com',
				},
				{
					id: 'e23',
					boothNumber: 174,
					media: ['food'],
					businessName: 'Bohman Bee Company',
					firstName: 'Kevin',
					lastName: 'Bohman',
					city: 'Hanover',
					state: 'IN',
					phone: '8122921076',
					email: 'bohmanbeecompany@gmail.com',
					businessUrl: 'www.bohmanbeecompany.com',
				},
				{
					id: 'e24',
					boothNumber: 176,
					media: ['food'],
					businessName: 'Monastery Baked Goods',
					firstName: 'Sisters of',
					lastName: 'St. Benedict',
					city: 'Ferdinand',
					state: 'IN',
					phone: '8123671411',
					email: 'bakedgoods@thedome.org',
					businessUrl: 'monasterybakedgoods.org',
				},
				{
					id: 'e25',
					boothNumber: 180,
					media: ['food'],
					businessName: 'Bee Great LLC',
					firstName: 'David',
					lastName: 'Mullins',
					city: 'Churubusco',
					state: 'IN',
					phone: '2602298356',
					email: 'beegreatcompany@gmail.com',
					businessUrl: 'beegreatlocal.com',
				},
			],
		};
	},
	mutations,
	actions,
	getters,
};
