import mutations from './mutations.js';
import actions from './actions.js';
import getters from './getters.js';

export default {
	namespaced: true,
	state() {
		return {
			exhibitors: [
				{
					id: 'e1',
					boothNumber: 101,
					media: ['natural/organic'],
					businessName: 'Making Good Scentz',
					firstName: 'Steven',
					lastName: 'Stivers',
					city: 'Bardstown',
					state: 'KY',
					phone: '5023648126',
					email: 'orders@makinggoodscentz.com',
					businessUrl: 'www.makinggoodscentz.com',
				},
				{
					id: 'e2',
					boothNumber: 107,
					media: ['wood', 'furniture'],
					businessName: 'Cole & Sons Inc, LLC',
					firstName: 'Andrew',
					lastName: 'Cole',
					city: 'Bowling Green',
					state: 'KY',
					phone: '7658609493',
					email: 'coleandsonsinc@gmail.com',
					businessUrl: 'www.coleandsonsinc.com',
				},
				{
					id: 'e3',
					boothNumber: 111,
					media: ['graphics'],
					businessName: 'Wiggins Artwork',
					firstName: 'Stephen',
					lastName: 'Wiggins',
					city: 'Lexington',
					state: 'KY',
					phone: '8596938172',
					email: 'coleandsonsinc@gmail.com',
					businessUrl: 'www.wigginsartwork.com',
				},
				{
					id: 'e4',
					boothNumber: 113,
					media: ['jewelry'],
					businessName: 'Mark Needham Jewelry',
					firstName: 'Mark',
					lastName: 'Needham',
					city: 'Louisville',
					state: 'KY',
					phone: '5028932851',
					email: 'mark@markneedhamjewelry.com',
					businessUrl: 'www.markneedhamjewelry.com', 
				},
				{
					id: 'e5',
					boothNumber: 120,
					media: ['natural/organic'],
					businessName: 'Peace of the Earth, LLC',
					firstName: 'Leslie',
					lastName: 'Delgado',
					city: 'Louisville',
					state: 'KY',
					phone: '5026905707',
					email: 'leslie@peaceoftheearth.com',
					businessUrl: 'www.peaceoftheearth.com', 
				},
				{
					id: 'e6',
					boothNumber: 122,
					media: ['ceramics'],
					businessName: 'Star Bird Pottery',
					firstName: 'Caroline',
					lastName: 'Zama',
					city: 'Louisville',
					state: 'KY',
					phone: '5024726533',
					email: 'caroline_zama@yahoo.com',
					businessUrl: 'www.starbirdpottery.com', 
				},
				{
					id: 'e7',
					boothNumber: 126,
					media: ['stone'],
					businessName: 'Stone Table Studio',
					firstName: 'Gary',
					lastName: 'DuBois',
					city: 'Berea',
					state: 'KY',
					phone: '8593148407',
					email: 'stonetablestudio@gmail.com',
					businessUrl: 'stonetablestudio.com', 
				},
				{
					id: 'e8',
					boothNumber: 128,
					media: ['sculpture', 'wood'],
					businessName: 'Jamie Green Sculpture',
					firstName: 'Jamie',
					lastName: 'Green',
					city: 'Lexington',
					state: 'KY',
					phone: '8594335426',
					email: 'jamiegreensculpture@gmail.com',
					businessUrl: 'www.jamiegreensculpture.com', 
				},
				{
					id: 'e9',
					boothNumber: 132,
					media: ['mixed media'],
					businessName: 'Ab Ova Art',
					firstName: 'Barbara',
					lastName: 'Stallard',
					city: 'Louisville',
					state: 'KY',
					phone: '5024349242',
					email: 'bcstallard@hotmail.com',
					businessUrl: 'abovaart.com', 
				},
				{
					id: 'e10',
					boothNumber: 134,
					media: ['fiber'],
					businessName: 'Blue Lick Hollow',
					firstName: 'Mary Ann',
					lastName: 'Woolery-Bussey',
					city: 'Berea',
					state: 'KY',
					phone: '8597563003',
					email: 'info@bluelickhollow.com',
					businessUrl: 'www.bluelickhollow.com', 
				},
				{
					id: 'e11',
					boothNumber: 140,
					media: ['fiber'],
					businessName: 'Anam Cara Art',
					firstName: 'Peggy',
					lastName: 'Modjeski',
					city: 'Louisville',
					state: 'KY',
					phone: '5027243333',
					email: 'woofsong@gmail.com',
					businessUrl: 'Anamcaraart.com', 
				},
				{
					id: 'e12',
					boothNumber: 142,
					media: ['ceramics'],
					businessName: 'Martin Studio',
					firstName: 'John',
					lastName: 'Martin',
					city: 'Beattyville',
					state: 'KY',
					phone: '8596619037',
					email: 'mrtnstudio@gmail.com',
					businessUrl: 'https://www.facebook.com/Martin-Studio-288004391392576/', 
				},
			],
		};
	},
	mutations,
	actions,
	getters,
};
