import mutations from './mutations.js';
import actions from './actions.js';
import getters from './getters.js';

export default {
	namespaced: true,
	state() {
		return {
			exhibitors: [
				{
					id: 'ex001',
					boothNumber: '101',
					media: ['Natural/Organic'],
					businessName: 'Making Good Scentz',
					firstName: 'Steven',
					lastName: 'Stivers',
					city: 'Bardstown',
					state: 'KY',
					phone: '5023648126',
					email: 'orders@makinggoodscentz.com',
					businessUrl: 'www.makinggoodscentz.com',
				},
				{
					id: 'ex002',
					boothNumber: '107',
					media: ['Wood', 'Furniture'],
					businessName: 'Cole & Sons Inc, LLC',
					firstName: 'Andrew',
					lastName: 'Cole',
					city: 'Bowling Green',
					state: 'KY',
					phone: '7658609493',
					email: 'coleandsonsinc@gmail.com',
					businessUrl: 'www.coleandsonsinc.com',
				},
				{
					id: 'ex003',
					boothNumber: '111',
					media: ['Graphics'],
					businessName: 'Wiggins Artwork',
					firstName: 'Stephen',
					lastName: 'Wiggins',
					city: 'Lexington',
					state: 'KY',
					phone: '8596938172',
					email: 'wigginsartwork@gmail.com',
					businessUrl: 'www.wigginsartwork.com',
				},
				{
					id: 'ex004',
					boothNumber: '113',
					media: ['Jewelry'],
					businessName: 'Mark Needham Jewelry',
					firstName: 'Mark',
					lastName: 'Needham',
					city: 'Louisville',
					state: 'KY',
					phone: '5028932851',
					email: 'mark@markneedhamjewelry.com',
					businessUrl: 'www.markneedhamjewelry.com#',
				},
				{
					id: 'ex005',
					boothNumber: '120',
					media: ['Natural/Organic'],
					businessName: 'Peace of the Earth, LLC',
					firstName: 'Leslie',
					lastName: 'Delgado',
					city: 'Louisville',
					state: 'KY',
					phone: '5026905707',
					email: 'leslie@peaceoftheearth.com',
					businessUrl: 'www.peaceoftheearth.com',
				},
				{
					id: 'ex006',
					boothNumber: '122',
					media: ['Ceramics'],
					businessName: 'Star Bird Pottery',
					firstName: 'Caroline',
					lastName: 'Zama',
					city: 'Louisville',
					state: 'KY',
					phone: '5024726533',
					email: 'caroline_zama@yahoo.com',
					businessUrl: 'www.starbirdpottery.com',
				},
				{
					id: 'ex007',
					boothNumber: '126',
					media: ['Stone'],
					businessName: 'Stone Table Studio',
					firstName: 'Gary',
					lastName: 'DuBois',
					city: 'Berea',
					state: 'KY',
					phone: '8593148407',
					email: 'stonetablestudio@gmail.com',
					businessUrl: 'stonetablestudio.com',
				},
				{
					id: 'ex008',
					boothNumber: '128',
					media: ['Sculpture', 'Wood'],
					businessName: 'Jamie Green Sculpture',
					firstName: 'Jamie',
					lastName: 'Green',
					city: 'Lexington',
					state: 'KY',
					phone: '8594335426',
					email: 'jamiegreensculpture@gmail.com',
					businessUrl: 'www.jamiegreensculpture.com',
				},
				{
					id: 'ex009',
					boothNumber: '132',
					media: ['Mixed Media'],
					businessName: 'Ab Ova Art',
					firstName: 'Barbara',
					lastName: 'Stallard',
					city: 'Louisville',
					state: 'KY',
					phone: '5024349242',
					email: 'bcstallard@hotmail.com',
					businessUrl: 'abovaart.com',
				},
				{
					id: 'ex010',
					boothNumber: '134',
					media: ['Fiber'],
					businessName: 'Blue Lick Hollow',
					firstName: 'Mary Ann',
					lastName: 'Woolery-Bussey',
					city: 'Berea',
					state: 'KY',
					phone: '8597563003',
					email: 'info@bluelickhollow.com',
					businessUrl: 'www.bluelickhollow.com',
				},
				{
					id: 'ex011',
					boothNumber: '140',
					media: ['Fiber'],
					businessName: 'Anam Cara Art',
					firstName: 'Peggy',
					lastName: 'Modjeski',
					city: 'Louisville',
					state: 'KY',
					phone: '5027243333',
					email: 'woofsong@gmail.com',
					businessUrl: 'Anamcaraart.com',
				},
				{
					id: 'ex012',
					boothNumber: '142',
					media: ['Ceramics'],
					businessName: 'Martin Studio',
					firstName: 'John',
					lastName: 'Martin',
					city: 'Beattyville',
					state: 'KY',
					phone: '8596619037',
					email: 'mrtnstudio@gmail.com',
					businessUrl: 'www.facebook.com/Martin-Studio-288004391392576/',
				},
				{
					id: 'ex013',
					boothNumber: '146',
					media: ['Baskets', 'Fiber', 'Natural/Organic'],
					businessName: 'Designer Baskets by Derek',
					firstName: 'Derek',
					lastName: 'Downing',
					city: 'Lexington',
					state: 'KY',
					phone: '8594893400',
					email: 'derek@designerbasketsbyderek.com',
					businessUrl: 'www.designerbasketsbyderek.com',
				},
				{
					id: 'ex014',
					boothNumber: '148',
					media: ['Fiber', 'Natural/Organic'],
					businessName: 'Cynthia Houston',
					firstName: 'Cynthia',
					lastName: 'Houston',
					city: 'Bowling Green',
					state: 'KY',
					phone: '2709017315',
					email: 'media3693@aol.com',
					businessUrl: 'cindyhouston.com',
				},
				{
					id: 'ex015',
					boothNumber: '150',
					media: ['Glass'],
					businessName: 'Chad Balster Glass',
					firstName: 'Chad',
					lastName: 'Balster',
					city: 'Louisville',
					state: 'KY',
					phone: '5023866319',
					email: 'chadbalsterglass@gmail.com',
					businessUrl: 'www.chadbalsterglass.com',
				},
				{
					id: 'ex016',
					boothNumber: '152',
					media: ['Drawing', 'Painting'],
					businessName: 'Art by Kathy Conroy',
					firstName: 'Kathleen',
					lastName: 'Conroy',
					city: 'Pleasureville',
					state: 'KY',
					phone: '5025427208',
					email: 'kathleensr@bellsouth.net',
					businessUrl: 'www.artbykathyconroy.com',
				},
				{
					id: 'ex017',
					boothNumber: '158',
					media: ['Painting'],
					businessName: 'Mels Art Works',
					firstName: 'Melanie',
					lastName: 'Wisdom',
					city: 'Lexington',
					state: 'KY',
					phone: '6066150022',
					email: 'melsartworks1@gmail.com',
					businessUrl: 'melsartworks.com',
				},
				{
					id: 'ex018',
					boothNumber: '160',
					media: ['Painting'],
					businessName: 'Ken Burney Art, LLC',
					firstName: 'Kenneth',
					lastName: 'Burney',
					city: 'Lexington',
					state: 'KY',
					phone: '3134097736',
					email: 'kenburneyart@gmail.com',
					businessUrl: 'www.kenburneyart.com',
				},
				{
					id: 'ex019',
					boothNumber: '161',
					media: ['Ceramics'],
					businessName: 'Egenolf Ceramics',
					firstName: 'Adam',
					lastName: 'Egenolf',
					city: 'Nineveh',
					state: 'IN',
					phone: '8126068775',
					email: 'egenolfceramics@gmail.com',
					businessUrl: 'www.egenolfceramics.com',
				},
				{
					id: 'ex020',
					boothNumber: '165',
					media: ['Publisher'],
					businessName: 'University Press of Kentucky',
					firstName: '',
					lastName: '',
					city: 'Lexington',
					state: 'KY',
					phone: '8592574249',
					email: 'brooke.raby@uky.edu',
					businessUrl: 'www.kentuckypress.com',
				},
				{
					id: 'ex021',
					boothNumber: '169',
					media: ['Publisher'],
					businessName: 'Acclaim Press',
					firstName: 'Doug',
					lastName: 'Sikes',
					city: 'Morley',
					state: 'MO',
					phone: '5734729800',
					email: 'dwsikes@acclaimpress.com',
					businessUrl: 'acclaimpress.com',
				},
				{
					id: 'ex022',
					boothNumber: '171',
					media: ['Publisher'],
					businessName: 'Kentucky Monthly Magazine',
					firstName: 'Stephen',
					lastName: 'Vest',
					city: 'Frankfort',
					state: 'KY',
					phone: '5022270053',
					email: 'kentuckymonthly@kentuckymonthly.com',
					businessUrl: 'kentuckymonthly.com',
				},
				{
					id: 'ex023',
					boothNumber: '174',
					media: ['Food'],
					businessName: 'Bohman Bee Company',
					firstName: 'Kevin',
					lastName: 'Bohman',
					city: 'Hanover',
					state: 'IN',
					phone: '8122921076',
					email: 'bohmanbeecompany@gmail.com',
					businessUrl: 'www.bohmanbeecompany.com',
				},
				{
					id: 'ex024',
					boothNumber: '176',
					media: ['Food'],
					businessName: 'Monastery Baked Goods',
					firstName: 'Sisters of',
					lastName: 'St. Benedict',
					city: 'Ferdinand',
					state: 'IN',
					phone: '8123671411',
					email: 'bakedgoods@thedome.org',
					businessUrl: 'monasterybakedgoods.org',
				},
				{
					id: 'ex025',
					boothNumber: '180',
					media: ['Food'],
					businessName: 'Bee Great LLC',
					firstName: 'David',
					lastName: 'Mullins',
					city: 'Churubusco',
					state: 'IN',
					phone: '2602298356',
					email: 'beegreatcompany@gmail.com',
					businessUrl: 'beegreatlocal.com',
				},
				{
					id: 'ex026',
					boothNumber: '188',
					media: ['Food'],
					businessName: 'Peppers-R-Paradise',
					firstName: 'David',
					lastName: 'Smith',
					city: 'Radcliff',
					state: 'KY',
					phone: '5027240213',
					email: 'peppersrparadise@comcast.net',
					businessUrl: 'www.peppersrparadise.com',
				},
				{
					id: 'ex027',
					boothNumber: '190',
					media: ['Food'],
					businessName: 'Kentucky Mountain Coffee',
					firstName: 'Jereta',
					lastName: 'Walters',
					city: 'Paintsville',
					state: 'KY',
					phone: '6063313884',
					email: 'jwalters.0310@gmail.com',
					businessUrl: 'www.kymtncoffee.com',
				},
				{
					id: 'ex028',
					boothNumber: '194',
					media: ['Food'],
					businessName: 'Friends Drift Inn',
					firstName: 'Joyce & Charles',
					lastName: 'Pinson',
					city: 'Pikeville',
					state: 'KY',
					phone: '6064330331',
					email: 'joyce@friendsdriftinn.com',
					businessUrl: 'friendsdriftinn.com',
				},
				{
					id: 'ex029',
					boothNumber: '196',
					media: ['Food'],
					businessName: 'The Sweet Shoppe',
					firstName: 'Patrick',
					lastName: 'Durham',
					city: 'Hodgenville',
					state: 'KY',
					phone: '2707353558',
					email: 'fudge@scrtc.com',
					businessUrl: 'www.sweetshoppehodgenville.com',
				},
				{
					id: 'ex030',
					boothNumber: '202',
					media: ['Food'],
					businessName: "Cappy's Caramel Corn",
					firstName: 'Brad',
					lastName: 'Wallace',
					city: 'Paris',
					state: 'KY',
					phone: '8593840533',
					email: 'brad@cappyscaramelcorn.com',
					businessUrl: 'www.cappyscaramelcorn.com',
				},
				{
					id: 'ex031',
					boothNumber: '212',
					media: ['Jewlery'],
					businessName: 'BSpoken Designs',
					firstName: 'Diana',
					lastName: 'Thomas',
					city: 'Georgetown',
					state: 'KY',
					phone: '5023706915',
					email: 'bspokendesigns@gmail.com',
					businessUrl: 'www.bspokendesigns.com',
				},
				{
					id: 'ex032',
					boothNumber: '213',
					media: ['Sculpure'],
					businessName: 'Yardbirds®',
					firstName: 'Richard',
					lastName: 'Kolb',
					city: 'Louisville',
					state: 'KY',
					phone: '5029052527',
					email: 'talentedsculptor@yahoo.com',
					businessUrl: 'yardbirds.info',
				},
				{
					id: 'ex033',
					boothNumber: '214',
					media: ['Wood'],
					businessName: 'TG Designs LLC',
					firstName: 'Eugene',
					lastName: 'King',
					city: 'Stanton',
					state: 'KY',
					phone: '6066638211',
					email: 'eking1953@yahoo.com',
					businessUrl: 'tgdesigns.net',
				},
				{
					id: 'ex034',
					boothNumber: '219',
					media: ['Natural/Organic'],
					businessName: 'Moss Hill Bath & Body Collection',
					firstName: 'Teri',
					lastName: 'Amsler',
					city: 'Louisville',
					state: 'KY',
					phone: '5023653405',
					email: 'mosshillweb@gmail.com',
					businessUrl: 'mosshill.net',
				},
				{
					id: 'ex035',
					boothNumber: '221',
					media: ['Ceramics', 'Mixed Media'],
					businessName: 'Studio Cat Walk',
					firstName: 'Keiko',
					lastName: 'Akiyama',
					city: 'Crestwood',
					state: 'KY',
					phone: '5025533217',
					email: 'kakiyama0325@gmail.com',
					businessUrl: '',
				},
				{
					id: 'ex036',
					boothNumber: '225',
					media: ['Jewelry'],
					businessName: 'A Small Extravagance',
					firstName: 'Cynthia',
					lastName: 'Pierce Roberts',
					city: 'Lexington',
					state: 'KY',
					phone: '8592690878',
					email: 'cindy@asmallextravagance.com',
					businessUrl: 'www.asmallextravagance.com',
				},
				{
					id: 'ex037',
					boothNumber: '227',
					media: ['Graphics', 'Mixed Media'],
					businessName: 'Starpointe Studio',
					firstName: 'Joanne',
					lastName: 'Price',
					city: 'Bagdad',
					state: 'KY',
					phone: '7633006004',
					email: 'joanne@starpointestudio.com',
					businessUrl: 'www.starpointestudio.com',
				},
				{
					id: 'ex038',
					boothNumber: '231',
					media: ['Leather', 'Mixed Media'],
					businessName: 'ReImagined by Luna',
					firstName: 'Melissa',
					lastName: 'Oesch',
					city: 'Lexington',
					state: 'KY',
					phone: '8594206536',
					email: 'reimaginedbyluna@gmail.com',
					businessUrl: 'www.reimaginedonline.com',
				},
				{
					id: 'ex039',
					boothNumber: '233',
					media: ['Painting'],
					businessName: 'Meadow House Studio',
					firstName: 'Laura',
					lastName: 'Poulette',
					city: 'Berea',
					state: 'KY',
					phone: '8599851602',
					email: 'laura.poulette@gmail.com',
					businessUrl: 'www.themeadowhousefarm.com',
				},
				{
					id: 'ex040',
					boothNumber: '237',
					media: ['Jewelry'],
					businessName: 'PhbeaD, LLC',
					firstName: 'Lisa',
					lastName: 'Senetar',
					city: 'Paint Lick',
					state: 'KY',
					phone: '8597792498',
					email: 'senetar@phbead.com',
					businessUrl: 'www.PhbeaD.com',
				},
				{
					id: 'ex041',
					boothNumber: '242',
					media: ['Ceramics', 'Sculpture'],
					businessName: 'Wiesener Studios',
					firstName: 'Fred',
					lastName: 'Wiesener',
					city: 'Maysville',
					state: 'KY',
					phone: '6064075243',
					email: 'wiesart@yahoo.com',
					businessUrl: 'wiesenerstudios.com',
				},
				{
					id: 'ex042',
					boothNumber: '243',
					media: ['Graphics'],
					businessName: 'Cricket Press',
					firstName: 'Sara & Brian',
					lastName: 'Turner',
					city: 'Lexington',
					state: 'KY',
					phone: '8594208599',
					email: 'cricketpress@gmail.com',
					businessUrl: 'www.cricket-press.com/',
				},
				{
					id: 'ex043',
					boothNumber: '244',
					media: ['Jewlery'],
					businessName: 'Sugar Mountain Jewelry',
					firstName: 'Jessica',
					lastName: 'Daman',
					city: 'Florence',
					state: 'KY',
					phone: '8596524158',
					email: 'jessica@sugarmountainjewelry.com',
					businessUrl: 'sugarmountainjewelry.com',
				},
				{
					id: 'ex044',
					boothNumber: '247',
					media: ['Jewelry, Natural/Organic'],
					businessName: 'Bridewell',
					firstName: 'Ray and Amy',
					lastName: 'Bridewell',
					city: 'Bellevue',
					state: 'KY',
					phone: '8598019174',
					email: 'bridewells@wegrowcrystals.com',
					businessUrl: 'www.bridewellstone.com',
				},
				{
					id: 'ex045',
					boothNumber: '251',
					media: ['Mixed Media'],
					businessName: 'FoleyPrints Studio',
					firstName: 'Elizabeth',
					lastName: 'Foley',
					city: 'Louisville',
					state: 'KY',
					phone: '8593514560',
					email: 'foleyprints@gmail.com',
					businessUrl: 'www.foleyprints.com',
				},
				{
					id: 'ex046',
					boothNumber: '253',
					media: ['Drawing', 'Mixed Media', 'Painting'],
					businessName: 'Rob Bridges Illustration',
					firstName: 'Robert',
					lastName: 'Bridges',
					city: 'Georgetown',
					state: 'KY',
					phone: '8599402228',
					email: 'robert@robbridges.com',
					businessUrl: 'www.robbridges.com',
				},
				{
					id: 'ex047',
					boothNumber: '257',
					media: ['Sculpture'],
					businessName: 'Michelle Hayden Fine Art',
					firstName: 'Michelle',
					lastName: 'Hayden',
					city: 'Richmond',
					state: 'KY',
					phone: '',
					email: 'mhbeneaththebark@gmail.com',
					businessUrl: 'www.michellhaydenfineart.com',
				},
				{
					id: 'ex048',
					boothNumber: '301',
					media: ['Ceramics'],
					businessName: 'Marianne Brown Pottery',
					firstName: 'Marianne',
					lastName: 'Brown',
					city: 'Lawrenceburg',
					state: 'KY',
					phone: '5026048220',
					email: 'stampedclay@kih.net',
					businessUrl: 'www.stamped-clay.com',
				},
				{
					id: 'ex049',
					boothNumber: '304',
					media: ['Photography'],
					businessName: 'Ralph Tyree Photography',
					firstName: 'Ralph',
					lastName: 'Tyree',
					city: 'Winchester',
					state: 'KY',
					phone: '8597492837',
					email: 'rht3579@hotmail.com',
					businessUrl: 'www.ralphtyreephotography.com',
				},
				{
					id: 'ex050',
					boothNumber: '305',
					media: ['Wood'],
					businessName: 'Jamie Donaldson, Woodturner',
					firstName: 'Jamie',
					lastName: 'Donaldson',
					city: 'Georgetown',
					state: 'KY',
					phone: '5028630168',
					email: 'jdonaldson14@aol.com',
					businessUrl: 'jamiedonaldsonwoodturner.com',
				},
				{
					id: 'ex051',
					boothNumber: '307',
					media: ['Mixed Media', 'Painting'],
					businessName: 'Dawna Scripps Creations',
					firstName: 'Dawna',
					lastName: 'Scripps',
					city: 'Lexington',
					state: 'KY',
					phone: '6154913810',
					email: 'dawnascrippsart@gmail.com',
					businessUrl: 'www.whimsythings.net',
				},
				{
					id: 'ex052',
					boothNumber: '308',
					media: ['Metal'],
					businessName: "Pod's Forge",
					firstName: 'David',
					lastName: 'Shadwick',
					city: 'Wilmore',
					state: 'KY',
					phone: '8596086356',
					email: 'shadwick@podsforge.com',
					businessUrl: 'www.podsforge.com',
				},
				{
					id: 'ex053',
					boothNumber: '311',
					media: ['Ceramics'],
					businessName: 'Showkitty Pottery',
					firstName: 'Jana',
					lastName: 'John',
					city: 'Louisville',
					state: 'KY',
					phone: '5022719428',
					email: 'showkitty@att.net',
					businessUrl: 'showkittypottery.com',
				},
				{
					id: 'ex054',
					boothNumber: '313',
					media: ['Glass'],
					businessName: 'Joy Lait Art Glass',
					firstName: 'Joy',
					lastName: 'Lait',
					city: 'Louisville',
					state: 'KY',
					phone: '5027779792',
					email: 'louflamer@gmail.com',
					businessUrl: 'joylaitartglass.com',
				},
				{
					id: 'ex055',
					boothNumber: '314',
					media: ['Painting'],
					businessName: "Lakshmi's Studio",
					firstName: 'Lakshmi',
					lastName: 'Sriraman',
					city: 'Lexington',
					state: 'KY',
					phone: '8596088898',
					email: 'lakshmi@shreedance.com',
					businessUrl: 'www.lakshmisstudio.com',
				},
				{
					id: 'ex056',
					boothNumber: '315',
					media: ['Glass', 'Sculpture'],
					businessName: 'Ann Klem Reflections, LLC',
					firstName: 'Ann',
					lastName: 'Klem',
					city: 'Fisherville',
					state: 'KY',
					phone: '5028178635',
					email: 'info@annklem.com',
					businessUrl: 'annklem.com',
				},
				{
					id: 'ex057',
					boothNumber: '318',
					media: ['Photography'],
					businessName: 'Dean Hill Photography',
					firstName: 'Dean',
					lastName: 'Hill',
					city: 'West Liberty',
					state: 'KY',
					phone: '6065223935',
					email: 'hilld@mrtc.com',
					businessUrl: 'www.deanhillphotography.com',
				},
				{
					id: 'ex058',
					boothNumber: '319',
					media: ['Ceramics', 'Sculpture'],
					businessName: 'K. Brown Pottery',
					firstName: 'Karen',
					lastName: 'Brown Levy',
					city: 'Louisville',
					state: 'KY',
					phone: '5024565013',
					email: 'kbrownpottery@gmail.com',
					businessUrl: 'kbrownpottery.etsy.com',
				},
				{
					id: 'ex059',
					boothNumber: '403',
					media: ['Drawing', 'Mixed Media', 'Painting'],
					businessName: 'Graviss Studios',
					firstName: 'Debbie',
					lastName: 'Graviss',
					city: 'Midway',
					state: 'KY',
					phone: '5023950158',
					email: 'info@gravissstudios.com',
					businessUrl: 'GravissStudios.com',
				},
				{
					id: 'ex060',
					boothNumber: '404',
					media: ['Mixed Media'],
					businessName: 'Xenosketch: the Art of Jason Sturgill',
					firstName: 'Jason',
					lastName: 'Sturgill',
					city: 'Lexington',
					state: 'KY',
					phone: '8597076093',
					email: 'Xenosketch@gmail.com',
					businessUrl: 'https://sites.google.com/view/xenosketchartofjasonsturgill',
				},
				{
					id: 'ex061',
					boothNumber: '407',
					media: ['Natural/Organic'],
					businessName: 'Rock Bottom Soap Company',
					firstName: 'Amy',
					lastName: 'Henson',
					city: 'London',
					state: 'KY',
					phone: '6062310707',
					email: 'rockbottomsoap@gmail.com',
					businessUrl: 'www.rockbottomsoap.com',
				},
				{
					id: 'ex062',
					boothNumber: '407',
					media: ['Natural/Organic'],
					businessName: 'Velvet Whiskey Candle Co',
					firstName: 'Kazzi',
					lastName: 'King',
					city: 'London',
					state: 'KY',
					phone: '6062317351',
					email: 'velvetwhiskeycandleco@gmail.com',
					businessUrl: 'www.velvetwhiskeycandle.com',
				},
				{
					id: 'ex063',
					boothNumber: '408',
					media: ['Baskets'],
					businessName: 'Handwoven Baskets by That Kentucky Lady®',
					firstName: 'Elizabeth',
					lastName: 'Worley',
					city: 'Lexington',
					state: 'KY',
					phone: '8592960115',
					email: 'tklbaskets@twc.com',
					businessUrl: '',
				},
				{
					id: 'ex064',
					boothNumber: '412',
					media: ['Ceramics'],
					businessName: 'Clay House Pots',
					firstName: 'Amy',
					lastName: 'Elswick',
					city: 'Louisville',
					state: 'KY',
					phone: '5025617878',
					email: 'amy@clayhousepots.com',
					businessUrl: 'clayhousepots.com',
				},
				{
					id: 'ex065',
					boothNumber: '413',
					media: ['Wood', 'Furniture'],
					businessName: 'Red Dog & Company',
					firstName: 'Michael',
					lastName: 'Angel',
					city: 'London',
					state: 'KY',
					phone: '6068788555',
					email: 'michaelaangel@msn.com',
					businessUrl: 'www.reddogchairs.com',
				},
				{
					id: 'ex066',
					boothNumber: '414',
					media: ['Jewlery'],
					businessName: 'Sawhorse Jewelry Designs',
					firstName: 'Martha',
					lastName: 'Wetter',
					city: 'Versailles',
					state: 'KY',
					phone: '8598738900',
					email: 'sawhorse@sawhorsejewelry.com',
					businessUrl: 'sawhorsejewelry.com',
				},
				{
					id: 'ex067',
					boothNumber: '500',
					media: ['Jewelry', 'Leather'],
					businessName: 'Leather By Design',
					firstName: 'Carin',
					lastName: 'Lovell',
					city: 'Lexington',
					state: 'KY',
					phone: '8596085742',
					email: 'carin@handrecrafted.com',
					businessUrl: 'handrecrafted.com',
				},
				{
					id: 'ex068',
					boothNumber: '502',
					media: ['Natural/Organic'],
					businessName: 'EarthyBrowns Natural Products',
					firstName: 'Paul',
					lastName: 'Brown',
					city: 'Louisville',
					state: 'KY',
					phone: '5027775293',
					email: 'paul@earthybrowns.com',
					businessUrl: 'earthybrowns.com',
				},
				{
					id: 'ex069',
					boothNumber: '503',
					media: ['Fiber'],
					businessName: 'Worker Bee Sewing Company LLC',
					firstName: 'Teresa',
					lastName: 'Webb',
					city: 'Berea',
					state: 'KY',
					phone: '8593123994',
					email: 'teresa@workerbeesewingco.com',
					businessUrl: 'www.workerbeesewingco.com',
				},
				{
					id: 'ex070',
					boothNumber: '504',
					media: ['Fiber'],
					businessName: 'Colors to Dye For',
					firstName: 'Mary',
					lastName: 'Nehring',
					city: 'Versailles',
					state: 'KY',
					phone: '8593960216',
					email: 'marynehringcolors2dye4@gmail.com',
					businessUrl: 'www.colors2dye4.com',
				},
				{
					id: 'ex071',
					boothNumber: '507',
					media: ['Jewelry'],
					businessName: 'Twelfth House Designs',
					firstName: 'Deb',
					lastName: 'Chenault',
					city: 'Berea',
					state: 'KY',
					phone: '8598688520',
					email: 'debchenault@12thhousedesigns.com',
					businessUrl: 'www.12thhousedesigns.com',
				},
				{
					id: 'ex072',
					boothNumber: '508',
					media: ['Glass'],
					businessName: 'Dan Neil Barnes Studios',
					firstName: 'Dan Neil',
					lastName: 'Barnes',
					city: 'Georgetown',
					state: 'KY',
					phone: '8595593171',
					email: 'danneilbarnes@gmail.com',
					businessUrl: 'danbarnesglassart.com',
				},
				{
					id: 'ex073',
					boothNumber: '511',
					media: ['Wood'],
					businessName: 'Sweet Sawdust',
					firstName: 'Curran',
					lastName: 'Copeland',
					city: 'Cadiz',
					state: 'KY',
					phone: '2705223878',
					email: 'sweetsawdust@bellsouth.net',
					businessUrl: 'sweetsawdust.com',
				},
				{
					id: 'ex074',
					boothNumber: '512',
					media: ['Wood'],
					businessName: 'Calan Originals',
					firstName: 'Alan & Cathe',
					lastName: 'Hedgespeth',
					city: 'Henderson',
					state: 'KY',
					phone: '2708605953',
					email: 'achedgespeth@twc.com',
					businessUrl: 'calan-originals.square.site',
				},
				{
					id: 'ex075',
					boothNumber: '513',
					media: ['Painting'],
					businessName: 'C.A. Walton Studio',
					firstName: 'Cheryle',
					lastName: 'Walton',
					city: 'Lexington',
					state: 'KY',
					phone: '6065603811',
					email: 'cheryle2857@gmail.com',
					businessUrl: 'www.etsy.com/hk-en/shop/CAWaltonStudios',
				},
				{
					id: 'ex076',
					boothNumber: '514',
					media: ['Painting'],
					businessName: 'Fine Art by Pamela Clegg',
					firstName: 'Pamela',
					lastName: 'Clegg',
					city: 'Georgetown',
					state: 'KY',
					phone: '5023162896',
					email: 'pmclegg1@gmail.com',
					businessUrl: 'pamelaclegg.com',
				},
				{
					id: 'ex077',
					boothNumber: '603',
					media: ['Photography'],
					businessName: 'Addison Williams Fine Art',
					firstName: 'Addison',
					lastName: 'Williams',
					city: 'Jenkins',
					state: 'KY',
					phone: '6145826160',
					email: 'addison@addisonwilliams.com',
					businessUrl: 'www.AddisonWilliams.com',
				},
				{
					id: 'ex078',
					boothNumber: '604',
					media: ['Furniture'],
					businessName: 'Classic Woodworking',
					firstName: 'Chris',
					lastName: 'Krauskopf',
					city: 'Louisville',
					state: 'KY',
					phone: '5029681778',
					email: 'christokk@netzero.com',
					businessUrl: 'www.therockingchairman.com',
				},
				{
					id: 'ex079',
					boothNumber: '606',
					media: ['Wood', 'Furniture'],
					businessName: 'Kentucky Oak Bourbon Barrel Furniture',
					firstName: 'Dave',
					lastName: 'Tucker',
					city: 'Louisville',
					state: 'KY',
					phone: '5026432469',
					email: 'dtucker.kyoak@gmail.com',
					businessUrl: 'kyoakbourbonbarrelfurniture.com',
				},
				{
					id: 'ex080',
					boothNumber: '610',
					media: ['Wood'],
					businessName: '',
					firstName: 'Chad',
					lastName: 'Eames',
					city: 'Lexington',
					state: 'KY',
					phone: '8595392423',
					email: 'chadeameswoodworks@gmail.com',
					businessUrl: 'chadeames.com',
				},
				{
					id: 'ex081',
					boothNumber: '611',
					media: ['Photography'],
					businessName: 'TLT Photography',
					firstName: 'Ted',
					lastName: 'Tarquinio',
					city: 'Louisville',
					state: 'KY',
					phone: '5025843020',
					email: 'tedtarquinio@gmail.com',
					businessUrl: 'www.tltphoto.com',
				},
				{
					id: 'ex082',
					boothNumber: '613',
					media: ['Jewelry'],
					businessName: "Jeannette's Jewelry/H & J Associates",
					firstName: 'Jeannette',
					lastName: 'Rowlett',
					city: 'Berea',
					state: 'KY',
					phone: '8592482505',
					email: 'info@jeannettesjewelry.com',
					businessUrl: '',
				},
				{
					id: 'ex083',
					boothNumber: '614',
					media: ['Metal', 'Sculpture'],
					businessName: 'Lloyd Hughes Metalsmithing',
					firstName: 'Lloyd',
					lastName: 'Hughes',
					city: 'Lexington',
					state: 'KY',
					phone: '8592271228',
					email: 'lloyd@hughesmetals.com',
					businessUrl: 'www.hughesmetals.com',
				},
				{
					id: 'ex084',
					boothNumber: '618',
					media: ['Ceramics'],
					businessName: 'Pottery by Thomas',
					firstName: 'Thomas',
					lastName: 'Porter',
					city: 'Philpot',
					state: 'KY',
					phone: '2703142402',
					email: 'potterybythomas@aol.com',
					businessUrl: '',
				},
				{
					id: 'ex085',
					boothNumber: '702',
					media: ['Fiber'],
					businessName: 'Fleece & Flax',
					firstName: 'Cecy',
					lastName: 'Thompson',
					city: 'Fisherville',
					state: 'KY',
					phone: '5022660011',
					email: 'cecyt@bellsouth.net',
					businessUrl: '',
				},
				{
					id: 'ex086',
					boothNumber: '702',
					media: ['Fiber'],
					businessName: 'Fleece & Flax',
					firstName: 'Susan',
					lastName: 'Grant',
					city: 'Louisville',
					state: 'KY',
					phone: '5024458341',
					email: 'susankgrant@bellsouth.net',
					businessUrl: '',
				},
				{
					id: 'ex087',
					boothNumber: '703',
					media: ['Ceramics'],
					businessName: 'Pawley Studios',
					firstName: 'Amanda',
					lastName: 'Pawley',
					city: 'Russellville',
					state: 'KY',
					phone: '8147688379',
					email: 'admin@pawleystudios.com',
					businessUrl: 'www.pawleystudios.com',
				},
				{
					id: 'ex088',
					boothNumber: '705',
					media: ['Natural/Organic'],
					businessName: 'Woodstock Lavender Co.',
					firstName: 'Allison',
					lastName: 'Horseman',
					city: 'Somerset',
					state: 'KY',
					phone: '8596089117',
					email: 'info@kylavender.com',
					businessUrl: 'www.woodstocklavender.com',
				},
				{
					id: 'ex089',
					boothNumber: '706',
					media: ['Jewelry'],
					businessName: 'Nora Swanson Arts',
					firstName: 'Nora',
					lastName: 'Swanson',
					city: 'Lexington',
					state: 'KY',
					phone: '8598662420',
					email: 'nswansonarts@gmail.com',
					businessUrl: 'www.nswansonarts.com',
				},
				{
					id: 'ex090',
					boothNumber: '708',
					media: ['Wood'],
					businessName: 'Scott Wilson Carpentry',
					firstName: 'Scott',
					lastName: 'Wilson',
					city: 'Lexington',
					state: 'KY',
					phone: '',
					email: 'scottwilsoncarpentry123@gmail.com',
					businessUrl: 'www.scottwilsoncarpentry.com',
				},
				{
					id: 'ex091',
					boothNumber: '709',
					media: ['Mixed Media', 'Natural Organic'],
					businessName: 'The Burned Gourd, LLC',
					firstName: 'Paul',
					lastName: 'Buhrmester',
					city: 'Bowling Green',
					state: 'KY',
					phone: '9018264318',
					email: 'theburnedgourd@gmail.com',
					businessUrl: 'theburnedgourd.com',
				},
				{
					id: 'ex092',
					boothNumber: '712',
					media: ['Mixed Media', 'Natural/Organic'],
					businessName: 'Haunts of Nature',
					firstName: 'Amelia',
					lastName: 'Arenson',
					city: 'Lawrenceburg',
					state: 'KY',
					phone: '2627077656',
					email: 'amelia.arenson@outlook.com',
					businessUrl: '',
				},
				{
					id: 'ex093',
					boothNumber: '713',
					media: ['Ceramics'],
					businessName: 'Anne Porter Elliott - Pottery',
					firstName: 'Anne',
					lastName: 'Elliott',
					city: 'Stamping Ground',
					state: 'KY',
					phone: '8593965684',
					email: 'anne@elliottpottery.net',
					businessUrl: 'www.elliottpottery.net',
				},
				{
					id: 'ex094',
					boothNumber: '714',
					media: ['Wood'],
					businessName: "Hunt's Woodcraft LLC",
					firstName: 'Ernest',
					lastName: 'Hunt',
					city: 'Lawrenceburg',
					state: 'KY',
					phone: '5026806581',
					email: 'huntswoodcraft@att.net',
					businessUrl: 'huntswoodcraft.com',
				},
				{
					id: 'ex095',
					boothNumber: '717',
					media: ['Baskets'],
					businessName: 'Bountiful Baskets by Jan',
					firstName: 'Jan',
					lastName: 'Treesh',
					city: 'Lexington',
					state: 'KY',
					phone: '8592850560',
					email: 'jan@bbbyjan.com',
					businessUrl: 'bbbyjan.com',
				},
				{
					id: 'ex096',
					boothNumber: '718',
					media: ['Photography'],
					businessName: 'Reckollect Photography, LLC',
					firstName: 'Larry',
					lastName: 'Smith',
					city: 'Pendleton',
					state: 'KY',
					phone: '5024070820',
					email: 'ldsmith@reckollectphotography.com',
					businessUrl: 'reckollectphotography.com',
				},
			],
		};
	},
	mutations,
	actions,
	getters,
};
